[target.x86_64-unknown-linux-gnu]
# Reverting to default linker because server disk space is full for clang/lld
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld", "-C", "target-cpu=native"]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]
